FROM python:3.10

WORKDIR /app

COPY ../requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ../src /app/src
COPY ../prompts /app/prompts
COPY ../.env /app/.env

WORKDIR /app/src

CMD ["chainlit", "run", "app.py", "--host", "0.0.0.0", "--port", "8000"]