FROM python:3.10

WORKDIR /app

COPY ../requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ../src /app/src
COPY ../prompts /app/prompts
COPY ../.env /app/.env

WORKDIR /app/src

# Add environment variables
ENV GEMINI_API_KEY=AIzaSyBnFlgDC2gwvwyvdK2Z3a1NryynJccBCiI
ENV COMPILER_URL=http://localhost:5000/execute

CMD ["chainlit", "run", "app.py", "--host", "0.0.0.0", "--port", "8000"]